load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "active_feedback_node",
    srcs = ["active_feedback_node.py"],
    deps = [
        "//src/lingdong_msgs:audio_result_py_proto", 
    ],
)